language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
before_script:
  - npm install -g grunt-cli
deploy:
 provider: s3
 access_key_id: "YFMklG9mGdb7etpFUnrzzFB5aBgmwP0QEeRhNXzfVMfp/sPXU9OhuKrvIZrVLNCYtlalZGIG+MnGRT4BgEdqU4xkzwZvrq2nzgzr6LRxhqNfD1vXpZxLgEIsKYCHa5mBmR+w16B9QllgNj4epINTVDqSDrdodfU25B+ryvUW/ZM="
 secret_access_key: "ghLAzXeESh/82lFwcT1jUhOgxFn88x4XAIZt+/1q1PXrD9iBd42C/AD9drkkaY2JwE0aGJkBuGAp+UvShUVNelzfEigPBMjSeyUwzbydiionQHmYvZi37SIfSYBvJ4t9Pi1f5MC2IMCtkWxojJRklgG7Scjpn404q83+ooBqLSA="
 bucket: "ahkneemay-deploy"
 skip_cleanup: true
 acl: public_read
 region: eu-west-1
 endpoint: s3-website-eu-west-1.amazonaws.com
